name: geodev-logicout
dependencies:
- python>=3.8.5
- pip
- pip:
  - pandas>=1.5.3
  - geopandas>=0.12.2
  - shapely>=1.7
  - pyproj>=2.6.1
  - packaging>=23.0
  - matplotlib==3.7.1
  - requests>=2.28.0
  - python-tsp==0.3.1
  - polyline
  - python-dotenv
  - seaborn==0.12.2
  - folium==0.14.0
  - mapclassify==2.5.0
  - xlrd>=2.0.1
  - tqdm
  
